version: 0.2

phases:
  install:
    commands:
      # - yum update -y
      # - yum install nginx -y
      # - systemctl start nginx
      # - systemctl enable nginx
        - yum update -y
        - yum install -y httpd
        # - systemctl start httpd
        # - systemctl enable httpd
      
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring HTTPD
artifacts:
  files:
    - /var/www/html/index.html
